Preserve data
Kel-nana/school_library pull request #6
Opened 2023-08-02 13:48 UTC by Mahamadou-Nouridine

In this Pr, my coding partner and I brought changes that include:

- On exit from the app save all the data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. `rentals.json`)
- On startup of the app load all data from files. Remember to handle the case when one or more of the files are missing.

2023-08-02 16:45 UTC, Munsa1 requested changes
Hi @Mahamadou-Nouridine @Kel-nana , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Able To Save People And Books :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 16:45 UTC, Munsa1 commented on classes/rental.rb
> +        'parent_permission' => @person.parent_permission
- [ ] Nice work, however, we have an error when the user tries to exit the app.
The error is raised on line 28 of the `rental.rb` file, where the code attempts to call parent_permission on an instance of the Teacher class. Based on the error message, the issue seems to be related to the serialization of the Teacher object into JSON format. The `to_json` method is called on a Teacher object, but the `parent_permission` method is not recognized, leading to the `NoMethodError`.
To fix this issue, you need to ensure that the Teacher class has a parent_permission method defined.

Screenshot of error
![image](https://github.com/Kel-nana/school_library/assets/81932478/114ee56a-8845-4f90-ab59-fde98d8f8677)

2023-08-02 16:45 UTC, Munsa1 commented on classes/rental.rb
> +    person.rentals << self
- [ ] Again there is an error in creating and saving a rental.  It seems like you are trying to add the current rental (self) to the rentals collection of a Book object (book). However, the book object is nil, which means it has not been instantiated properly.
To fix this issue, ensure that you properly create and initialize the book object before using it. You should make sure that you have an instance of the Book class and that it is correctly associated with the Rental class.
 
e.g

```
class Rental
  attr_accessor :date, :book, :person

  def initialize(date, book, person)
    @date = date
    @book = book
    @person = person

    # Make sure to initialize the rentals array for the associated book.
    @book.rentals ||= []
    @book.rentals << self
  end
end
```


Screenshot
![image](https://github.com/Kel-nana/school_library/assets/81932478/b63cfefd-c60b-4045-ba9b-a9251fb693e8)

2023-08-03 10:48 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Mahamadou-Nouridine and @Kel-nana 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 13:05 UTC, merged